// src/components/telemedicine/ChatInterface.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Icon } from '@iconify/vue';

interface Message {
  role: 'patient' | 'doctor';
  text: string;
  time: string;
}

const messages = ref<Message[]>([
  { role: 'doctor', text: 'Hello! I can see your pre-consultation form. How are you feeling today?', time: 'Just now' },
]);
const newMessage = ref('');

const sendMessage = () => {
  if (!newMessage.value.trim()) return;
  messages.value.push({ role: 'patient', text: newMessage.value, time: 'Just now' });
  newMessage.value = '';
  setTimeout(() => {
    messages.value.push({ role: 'doctor', text: 'Thank you for sharing that. I\'ll look into your symptoms.', time: 'Just now' });
  }, 1500);
};
</script>

<template>
  <div class="flex flex-col h-full bg-gray-800 rounded-lg overflow-hidden" style="min-height:300px">
    <div class="px-3 py-2 border-b border-gray-700">
      <h3 class="text-white text-sm font-medium flex items-center">
        <Icon icon="fa6-solid:comment" class="mr-2 text-primary" /> Chat
      </h3>
    </div>
    <div class="flex-1 overflow-y-auto p-3 space-y-3">
      <div
        v-for="(msg, index) in messages"
        :key="index"
        :class="['flex', msg.role === 'patient' ? 'justify-end' : 'justify-start']"
      >
        <div :class="['max-w-xs px-3 py-2 rounded-lg text-sm', msg.role === 'patient' ? 'bg-primary text-white' : 'bg-gray-700 text-gray-200']">
          <p>{{ msg.text }}</p>
          <p class="text-xs opacity-70 mt-1">{{ msg.time }}</p>
        </div>
      </div>
    </div>
    <div class="p-3 border-t border-gray-700">
      <div class="flex space-x-2">
        <input
          v-model="newMessage"
          @keyup.enter="sendMessage"
          type="text"
          placeholder="Type a message..."
          class="flex-1 bg-gray-700 text-white placeholder-gray-400 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary"
        />
        <button @click="sendMessage" class="p-2 bg-primary hover:bg-primary/90 text-white rounded-lg transition-colors">
          <Icon icon="fa6-solid:paper-plane" />
        </button>
      </div>
    </div>
  </div>
</template>

// src/components/telemedicine/ChatInterface.jsx
import { useState } from 'react';
import { FaTimes, FaPaperPlane } from 'react-icons/fa';

const ChatInterface = ({ onClose }) => {
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState([
    { id: 1, sender: 'doctor', text: 'Hello! How can I help you today?' },
  ]);

  const handleSend = () => {
    if (message.trim()) {
      setMessages(prev => [...prev, { id: Date.now(), sender: 'patient', text: message }]);
      setMessage('');
      
      // Simulate doctor response
      setTimeout(() => {
        setMessages(prev => [...prev, {
          id: Date.now(),
          sender: 'doctor',
          text: 'Thank you for sharing. Let me review your symptoms...'
        }]);
      }, 1000);
    }
  };

  return (
    <div className="flex flex-col h-full">
      <div className="p-4 border-b flex justify-between items-center">
        <h3 className="font-semibold">Chat with Dr. Sarah</h3>
        <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
          <FaTimes />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map(msg => (
          <div
            key={msg.id}
            className={`flex ${msg.sender === 'patient' ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[80%] rounded-lg p-3 ${
                msg.sender === 'patient'
                  ? 'bg-primary text-white'
                  : 'bg-gray-100 text-gray-800'
              }`}
            >
              {msg.text}
            </div>
          </div>
        ))}
      </div>

      <div className="p-4 border-t">
        <div className="flex space-x-2">
          <input
            type="text"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            placeholder="Type your message..."
            className="flex-1 px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            onKeyPress={(e) => e.key === 'Enter' && handleSend()}
          />
          <button
            onClick={handleSend}
            className="px-4 py-2 bg-primary text-white rounded-md hover:bg-primary/90"
          >
            <FaPaperPlane />
          </button>
        </div>
      </div>
    </div>
  );
};

export default ChatInterface;
