// src/components/SEO.jsx
import { Helmet } from 'react-helmet-async';
import PropTypes from 'prop-types';

/**
 * SEO Component for dynamic meta tags on each page
 * Optimized for Maternity, Antenatal, Gynaecologist, and Obstetrician searches in Uganda/Jinja
 */
const SEO = ({
  title = 'Specialist Doctors International',
  description = 'Best maternity care, antenatal services, gynaecologist and obstetrician consultations in Jinja, Uganda. Expert prenatal care and safe deliveries.',
  keywords = 'maternity Jinja, antenatal Uganda, gynaecologist Jinja, obstetrician Uganda',
  image = '/images/SDI_Logo.png',
  url = 'https://www.specialistdoctors-international.org/',
  type = 'website',
  robots = ''
}) => {
  const fullTitle = title.includes('Specialist Doctors International') 
    ? title 
    : `${title} | Specialist Doctors International - Jinja, Uganda`;

  const baseKeywords = 'maternity Jinja, maternity Uganda, antenatal care Jinja, antenatal Uganda, gynaecologist Jinja, gynaecologist Uganda, obstetrician Jinja, obstetrician Uganda, prenatal care Uganda, pregnancy care Jinja, women\'s health Uganda';
  const fullKeywords = keywords ? `${keywords}, ${baseKeywords}` : baseKeywords;

  const fullImageUrl = image.startsWith('http') 
    ? image 
    : `https://www.specialistdoctors-international.org${image}`;

  const organizationSchema = {
    '@context': 'https://schema.org',
    '@type': 'MedicalOrganization',
    name: 'Specialist Doctors International',
    url: 'https://www.specialistdoctors-international.org/',
    logo: 'https://www.specialistdoctors-international.org/images/SDI_Logo.png',
    sameAs: [
      'https://www.facebook.com/specialistdoctorsintl/',
      'https://www.linkedin.com/company/specialist-doctors-international',
    ],
  };

  return (
    <Helmet>
      {/* Organization structured data for search engines */}
      <script type="application/ld+json">
        {JSON.stringify(organizationSchema)}
      </script>

      {/* Primary Meta Tags */}
      <title>{fullTitle}</title>
      <meta name="title" content={fullTitle} />
      <meta name="description" content={description} />
      <meta name="keywords" content={fullKeywords} />
      {robots && <meta name="robots" content={robots} />}
      
      {/* Canonical URL */}
      <link rel="canonical" href={url} />
      
      {/* Open Graph / Facebook */}
      <meta property="og:type" content={type} />
      <meta property="og:url" content={url} />
      <meta property="og:title" content={fullTitle} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={fullImageUrl} />
      <meta property="og:locale" content="en_UG" />
      
      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:url" content={url} />
      <meta name="twitter:title" content={fullTitle} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={fullImageUrl} />
    </Helmet>
  );
};

SEO.propTypes = {
  title: PropTypes.string,
  description: PropTypes.string,
  keywords: PropTypes.string,
  image: PropTypes.string,
  url: PropTypes.string,
  type: PropTypes.string,
  robots: PropTypes.string
};

export default SEO;

// src/components/SEO.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useHead } from '@unhead/vue';

interface Props {
  title?: string;
  description?: string;
  keywords?: string;
  image?: string;
  url?: string;
  type?: string;
  robots?: string;
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Specialist Doctors International',
  description: 'Best maternity care, antenatal services, gynaecologist and obstetrician consultations in Jinja, Uganda.',
  keywords: 'maternity Jinja, antenatal Uganda, gynaecologist Jinja, obstetrician Uganda',
  image: '/images/SDI_Logo.png',
  url: 'https://www.specialistdoctors-international.org/',
  type: 'website',
  robots: '',
});

const fullTitle = computed(() =>
  props.title.includes('Specialist Doctors International')
    ? props.title
    : `${props.title} | Specialist Doctors International - Jinja, Uganda`,
);

const baseKeywords =
  "maternity Jinja, maternity Uganda, antenatal care Jinja, antenatal Uganda, gynaecologist Jinja, gynaecologist Uganda, obstetrician Jinja, obstetrician Uganda, prenatal care Uganda, pregnancy care Jinja, women's health Uganda";

const fullKeywords = computed(() =>
  props.keywords ? `${props.keywords}, ${baseKeywords}` : baseKeywords,
);

const fullImageUrl = computed(() =>
  props.image.startsWith('http')
    ? props.image
    : `https://www.specialistdoctors-international.org${props.image}`,
);

const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'MedicalOrganization',
  name: 'Specialist Doctors International',
  url: 'https://www.specialistdoctors-international.org/',
  logo: 'https://www.specialistdoctors-international.org/images/SDI_Logo.png',
  sameAs: [
    'https://www.facebook.com/specialistdoctorsintl/',
    'https://www.linkedin.com/company/specialist-doctors-international',
  ],
};

useHead(
  computed(() => ({
    title: fullTitle.value,
    link: [{ rel: 'canonical', href: props.url }],
    meta: [
      { name: 'title', content: fullTitle.value },
      { name: 'description', content: props.description },
      { name: 'keywords', content: fullKeywords.value },
      ...(props.robots ? [{ name: 'robots', content: props.robots }] : []),
      { property: 'og:type', content: props.type },
      { property: 'og:url', content: props.url },
      { property: 'og:title', content: fullTitle.value },
      { property: 'og:description', content: props.description },
      { property: 'og:image', content: fullImageUrl.value },
      { property: 'og:locale', content: 'en_UG' },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:url', content: props.url },
      { name: 'twitter:title', content: fullTitle.value },
      { name: 'twitter:description', content: props.description },
      { name: 'twitter:image', content: fullImageUrl.value },
    ],
    script: [
      {
        type: 'application/ld+json',
        children: JSON.stringify(organizationSchema),
      },
    ],
  })),
);
</script>

<template>
  <!-- Headless — all output goes to <head> via @unhead/vue -->
</template>
